name: Upstream Google Kernel 5.15 ACK

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  sync-upstream:t
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: google
          fetch-depth: 0

      - name: Setup Git Configuration
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global http.postBuffer 524288000

      - name: Exact Tree Mirror from Upstream
        run: |
          git remote add upstream https://android.googlesource.com/kernel/common
          
          echo "Looking for the latest updates from upstream..."
          git fetch upstream android13-5.15-2023-08
          
          UPSTREAM_TREE=$(git rev-parse upstream/android13-5.15-lts^{tree})
          LOCAL_TREE=$(git rev-parse HEAD^{tree})
          
          if [ "$UPSTREAM_TREE" = "$LOCAL_TREE" ]; then
            echo "The source kernel is already identical to Google's upstream. There's nothing to push."
          else
            echo "Discrepancies found (Modified/Added/Deleted)! Performing mirror sync..."
            
            COMMIT_MSG="Merge upstream: android13-5.15-lts"
            NEW_COMMIT=$(git commit-tree "$UPSTREAM_TREE" -p HEAD -m "$COMMIT_MSG")
            
            git reset --hard "$NEW_COMMIT"
            
            git push origin google
            
            echo "Sync mirror successfully pushed to upstream!"
          fi
